### ISSUE TITLE
Implement CI using GitHub Actions

### ISSUE THREAD

**Issue by davitovmasyan** [davitovmasyan/dj-project#8]
Should check code style using `flake8` and run tests using `pytest`.

**Comment by rosdyana** [comment]
Hi, may I help you on this issue?

**Comment by davitovmasyan** [comment]
@rosdyana sure. Do you have any questions?

**Comment by davitovmasyan** [comment]
@rosdyana I checked [this](https://github.com/rosdyana/dj-project/commit/f2dc6594e70806742a0c832d16288a7c442d225b/checks?check_suite_id=245857855#step:6:40). And suggest to do the following, before running tests make sure you have installed all packages from `requirements/requiremens-test.txt` list.

**Comment by rosdyana** [comment]
Hi @davitovmasyan thank you for the suggestion, this is the PR #9 . thanks!
